pipeline {
    agent any

    environment {
        BACKEND_IMAGE = "albertxp/todo-server:latest"
        FRONTEND_IMAGE = "albertxp/todo-client:latest"
        KUBECONFIG = "/var/lib/jenkins/.kube/config"
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/bertoale/env.git', branch: 'main'
            }
        }

        stage('Build Docker Images') {
            options {
                timeout(time: 20, unit: 'MINUTES')
            }
            steps {
                dir('backend') {
                    sh "docker build  -t $BACKEND_IMAGE ."
                }
                dir('client') {
                    sh "docker build -t $FRONTEND_IMAGE ."
                }
            }
        }

        stage('Push to Docker Hubs') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh "docker push $BACKEND_IMAGE"
                    sh "docker push $FRONTEND_IMAGE"
                }
            }
        }

        stage('Deploy to K3s') {
            steps {
                withEnv(["KUBECONFIG=/var/lib/jenkins/.kube/config"]) {
                    sh 'bash server-deploy.sh'
                    sh 'bash client-deploy.sh'

                }
            }
        }
    }
}
